#############################################################################
# Makefile for building: NetAnim
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Dec 6 05:16:50 2013
# Project:  NetAnim.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile NetAnim.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DNS3_LOG_ENABLE -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		log.cpp \
		fatal-error.cpp \
		fatal-impl.cpp \
		logqt.cpp \
		resizeableitem.cpp \
		animnode.cpp \
		animatorscene.cpp \
		animpacket.cpp \
		netanim.cpp \
		animatormode.cpp \
		mode.cpp \
		animxmlparser.cpp \
		animatorview.cpp \
		animlink.cpp \
		animresource.cpp \
		statsview.cpp \
		statsmode.cpp \
		routingxmlparser.cpp \
		routingstatsscene.cpp \
		interfacestatsscene.cpp \
		flowmonxmlparser.cpp \
		flowmonstatsscene.cpp \
		textbubble.cpp moc_animatorscene.cpp \
		moc_animpacket.cpp \
		moc_netanim.cpp \
		moc_animatormode.cpp \
		moc_statsmode.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		log.o \
		fatal-error.o \
		fatal-impl.o \
		logqt.o \
		resizeableitem.o \
		animnode.o \
		animatorscene.o \
		animpacket.o \
		netanim.o \
		animatormode.o \
		mode.o \
		animxmlparser.o \
		animatorview.o \
		animlink.o \
		animresource.o \
		statsview.o \
		statsmode.o \
		routingxmlparser.o \
		routingstatsscene.o \
		interfacestatsscene.o \
		flowmonxmlparser.o \
		flowmonstatsscene.o \
		textbubble.o \
		moc_animatorscene.o \
		moc_animpacket.o \
		moc_netanim.o \
		moc_animatormode.o \
		moc_statsmode.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		NetAnim.pro
QMAKE_TARGET  = NetAnim
DESTDIR       = 
TARGET        = NetAnim

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NetAnim.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile NetAnim.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile NetAnim.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/NetAnim1.0.0 || $(MKDIR) .tmp/NetAnim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NetAnim1.0.0/ && $(COPY_FILE) --parents log.h fatal-error.h fatal-impl.h abort.h assert.h logqt.h animatorconstants.h resizeableitem.h animnode.h common.h animatorscene.h timevalue.h animpacket.h netanim.h animatormode.h animatorview.h mode.h animxmlparser.h animevent.h animlink.h animresource.h statsview.h statsmode.h statisticsconstants.h routingxmlparser.h routingstatsscene.h interfacestatsscene.h flowmonxmlparser.h flowmonstatsscene.h textbubble.h .tmp/NetAnim1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/NetAnim1.0.0/ && $(COPY_FILE) --parents main.cpp log.cpp fatal-error.cpp fatal-impl.cpp logqt.cpp resizeableitem.cpp animnode.cpp animatorscene.cpp animpacket.cpp netanim.cpp animatormode.cpp mode.cpp animxmlparser.cpp animatorview.cpp animlink.cpp animresource.cpp statsview.cpp statsmode.cpp routingxmlparser.cpp routingstatsscene.cpp interfacestatsscene.cpp flowmonxmlparser.cpp flowmonstatsscene.cpp textbubble.cpp .tmp/NetAnim1.0.0/ && (cd `dirname .tmp/NetAnim1.0.0` && $(TAR) NetAnim1.0.0.tar NetAnim1.0.0 && $(COMPRESS) NetAnim1.0.0.tar) && $(MOVE) `dirname .tmp/NetAnim1.0.0`/NetAnim1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NetAnim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_animatorscene.cpp moc_animpacket.cpp moc_netanim.cpp moc_animatormode.cpp moc_statsmode.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_animatorscene.cpp moc_animpacket.cpp moc_netanim.cpp moc_animatormode.cpp moc_statsmode.cpp
moc_animatorscene.cpp: common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animnode.h \
		resizeableitem.h \
		animatorconstants.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorscene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) animatorscene.h -o moc_animatorscene.cpp

moc_animpacket.cpp: common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatorconstants.h \
		timevalue.h \
		animevent.h \
		animpacket.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) animpacket.h -o moc_animpacket.cpp

moc_netanim.cpp: common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		mode.h \
		netanim.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) netanim.h -o moc_netanim.cpp

moc_animatormode.cpp: common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h \
		mode.h \
		animatormode.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) animatormode.h -o moc_animatormode.cpp

moc_statsmode.cpp: common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		mode.h \
		statsmode.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) statsmode.h -o moc_statsmode.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		animator_grid.svg \
		animator_pause.svg \
		animator_nodeid.svg \
		animator_zoomin.svg \
		animator_reload.svg \
		animator_fileopen.svg \
		animator_showpackets.svg \
		animator_wirelesscircles.svg \
		ns3logo2.png \
		animator_play.svg \
		animator_zoomout.svg
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp netanim.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		mode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

log.o: log.cpp log.h \
		assert.h \
		fatal-error.h \
		fatal-impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log.o log.cpp

fatal-error.o: fatal-error.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fatal-error.o fatal-error.cpp

fatal-impl.o: fatal-impl.cpp fatal-impl.h \
		log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fatal-impl.o fatal-impl.cpp

logqt.o: logqt.cpp logqt.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animpacket.h \
		animatorconstants.h \
		timevalue.h \
		animevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logqt.o logqt.cpp

resizeableitem.o: resizeableitem.cpp resizeableitem.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatorconstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resizeableitem.o resizeableitem.cpp

animnode.o: animnode.cpp animnode.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		resizeableitem.h \
		animatorconstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animnode.o animnode.cpp

animatorscene.o: animatorscene.cpp animatorscene.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animnode.h \
		resizeableitem.h \
		animatorconstants.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animatorscene.o animatorscene.cpp

animpacket.o: animpacket.cpp animpacket.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatorconstants.h \
		timevalue.h \
		animevent.h \
		animnode.h \
		resizeableitem.h \
		animatorview.h \
		animatorscene.h \
		animlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animpacket.o animpacket.cpp

netanim.o: netanim.cpp netanim.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		mode.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h \
		statsmode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netanim.o netanim.cpp

animatormode.o: animatormode.cpp common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h \
		mode.h \
		animxmlparser.h \
		animresource.h \
		statsmode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animatormode.o animatormode.cpp

mode.o: mode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mode.o mode.cpp

animxmlparser.o: animxmlparser.cpp animxmlparser.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animevent.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animatorview.h \
		mode.h \
		animresource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animxmlparser.o animxmlparser.cpp

animatorview.o: animatorview.cpp animatorview.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animatorconstants.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animatorview.o animatorview.cpp

animlink.o: animlink.cpp animnode.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		resizeableitem.h \
		animatorconstants.h \
		animlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animlink.o animlink.cpp

animresource.o: animresource.cpp animresource.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animresource.o animresource.cpp

statsview.o: statsview.cpp statsview.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statsview.o statsview.cpp

statsmode.o: statsmode.cpp animatorscene.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animnode.h \
		resizeableitem.h \
		animatorconstants.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatormode.h \
		animatorview.h \
		mode.h \
		routingxmlparser.h \
		statisticsconstants.h \
		statsmode.h \
		statsview.h \
		interfacestatsscene.h \
		routingstatsscene.h \
		flowmonstatsscene.h \
		flowmonxmlparser.h \
		textbubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statsmode.o statsmode.cpp

routingxmlparser.o: routingxmlparser.cpp routingxmlparser.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		statsmode.h \
		mode.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h \
		routingstatsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o routingxmlparser.o routingxmlparser.cpp

routingstatsscene.o: routingstatsscene.cpp routingstatsscene.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		timevalue.h \
		routingxmlparser.h \
		textbubble.h \
		statisticsconstants.h \
		statsmode.h \
		mode.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		animpacket.h \
		animevent.h \
		animatorview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o routingstatsscene.o routingstatsscene.cpp

interfacestatsscene.o: interfacestatsscene.cpp interfacestatsscene.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		textbubble.h \
		statisticsconstants.h \
		statsmode.h \
		mode.h \
		animlink.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interfacestatsscene.o interfacestatsscene.cpp

flowmonxmlparser.o: flowmonxmlparser.cpp flowmonxmlparser.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		animatormode.h \
		animatorconstants.h \
		animatorscene.h \
		animnode.h \
		resizeableitem.h \
		animlink.h \
		timevalue.h \
		animpacket.h \
		animevent.h \
		animatorview.h \
		mode.h \
		flowmonstatsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowmonxmlparser.o flowmonxmlparser.cpp

flowmonstatsscene.o: flowmonstatsscene.cpp statsmode.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h \
		mode.h \
		flowmonstatsscene.h \
		timevalue.h \
		flowmonxmlparser.h \
		statisticsconstants.h \
		textbubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowmonstatsscene.o flowmonstatsscene.cpp

textbubble.o: textbubble.cpp textbubble.h \
		common.h \
		log.h \
		fatal-error.h \
		fatal-impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textbubble.o textbubble.cpp

moc_animatorscene.o: moc_animatorscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animatorscene.o moc_animatorscene.cpp

moc_animpacket.o: moc_animpacket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animpacket.o moc_animpacket.cpp

moc_netanim.o: moc_netanim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_netanim.o moc_netanim.cpp

moc_animatormode.o: moc_animatormode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animatormode.o moc_animatormode.cpp

moc_statsmode.o: moc_statsmode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statsmode.o moc_statsmode.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

